.\" This is an -*- nroff -*- source file.
.\" Author: Enrique Zanardi
.TH UNTEX 1 "14th March 1997"
.SH NAME
untex \- Remove LaTeX commands from input
.SH SYNOPSIS
.B untex
[\-o] [\-a] [\-m] [\-e] [\-u[iso,ascii]] [\-g[iso,ascii]] file1 [file2]  ...
.SH DESCRIPTION
.B untex
removes all LaTeX commands from file1, extracting the contents to
stdout. If file1 is "-", stdin will be used.
.SH OPTIONS
.TP
.I "\-a"
Remove arguments. Implies
.I \-o
.TP
.I "\-e"
Remove environment names.
.TP
.I "\-g"
Replace all "a (etc.) with ibm characters (german.sty). Implies
.I \-u
.TP
.I "\-m"
Remove all math
.TP
.I "\-o"
Remove options to commands
.TP
.I "\-u"
Replace all \\"a (etc.) with ibm characters
.SH SEE ALSO
.BR tex (1).
.SH AUTHOR
.B untex
was written by Michael Staats. This manpage was written by Enrique
Zanardi.
